export { default as Dashboard } from './dashboard/Dashboard'
export { default as Login } from './login/Login'
export { default as Cadastro } from './cadastro/Cadastro'
export { default as Homepage } from './homepage/Homepage'
export { default as HomepageCadastro} from './homepagecadastro/HomepageCadastro'